const getNewNPC = () => {
  let heritage = getRandomItem(Heritage);
  let gender = getRandomItem(Gender);
  let looks = getRandomItem(appearances);
  let goal = getRandomItem(goals);
  let preferredMethod = getRandomItem(preferredMethods);
  let professionType = getRandomItem(professionTypes);
  let profession = professionType === "common" ? getRandomItem(commonProfessions) : getRandomItem(rareProfessions);
  let style = getRandomItem(styles);
  let trait = getRandomItem(traits);
  let interest = getRandomItem(interests);
  let quirk = getRandomItem(quirks);
  let firstName = getRandomItem(firstNames);
  let lastName = getRandomItem(lastNames);
  let alias = getRandomItem(aliases);

  return {
    heritage,
    gender,
    looks,
    goal,
    preferredMethod,
    profession,
    style,
    trait,
    interest,
    quirk,
    fullName: `${firstName} "${alias}" ${lastName}`
  };
}

export default getNewNPC;

const getRandomItem = (givenArray) => {
  return givenArray[Math.floor(Math.random() * givenArray.length)];
}

const Heritage = [
  "akorosi",
  "akorosi",
  "akorosi",
  "skovlander",
  "skovlander",
  "iruvian",
  "dagger islander",
  "severosi",
  "tycherosi"
];

const Gender = [
  "male",
  "female",
  "ambiguous/concealed"
];

const appearances = [
  "large",
  "slim",
  "bony",
  "short",
  "cute",
  "disfigured",
  "maimed",
  "lovely",
  "dark",
  "worn",
  "tall",
  "plain",
  "glasses",
  "monocle",
  "weathered",
  "fair",
  "rough",
  "sexy",
  "old",
  "prosthetic",
  "crippled",
  "chiseled",
  "stout",
  "plump",
  "wild",
  "young",
  "long hair",
  "beard",
  "wig",
  "handsome",
  "delicate",
  "wiry",
  "elegant",
  "stylish",
  "shorn",
  "bald",
  "athletic",
  "scarred",
  "striking",
  "stooped",
  "strange",
  "tattooed"
];

const goals = [
  "wealth",
  "pleasure",
  "respect",
  "power",
  "revenge",
  "love",
  "authority",
  "freedom",
  "change",
  "presige",
  "fame",
  "achievement",
  "chaos",
  "destruction",
  "control",
  "happiness",
  "justice",
  "knowledge",
  "infamy",
  "fear",
  "cooperation"
];

const preferredMethods = [
  "violence",
  "theft",
  "subterfuge",
  "threats",
  "arcane",
  "alchemy",
  "negotiation",
  "commerce",
  "blackmail",
  "study",
  "hard work",
  "teamwork",
  "manipulation",
  "law",
  "politics",
  "espionage",
  "strategy",
  "sabotage",
  "chaos"
];

const professionTypes = [
  "common",
  "rare"
];

const commonProfessions = [
  "baker",
  "cartwright",
  "driver",
  "leatherworker",
  "servant",
  "vendor",
  "barber",
  "chandler",
  "dyer",
  "mason",
  "shipwright",
  "weaver",
  "blacksmith",
  "clerk",
  "embroiderer",
  "merchant",
  "criminal",
  "woodworker",
  "brewer",
  "cobbler",
  "fishmonger",
  "roofer",
  "tailor",
  "goat herd",
  "butcher",
  "cooper",
  "gondolier",
  "ropemaker",
  "tanner",
  "messenger",
  "carpenter",
  "cultivator",
  "guard",
  "rug maker",
  "tinkerer",
  "sailor"
];

const rareProfessions = [
  "advocate",
  "banker",
  "diplomat",
  "musician",
  "sparkwright",
  "captain",
  "architect",
  "bounty hunter",
  "jailer",
  "physicker",
  "tax collector",
  "spirit warden",
  "artist",
  "clockmaker",
  "jeweler",
  "plumber",
  "treasurer",
  "journalist",
  "author",
  "courtesan",
  "leech",
  "printer",
  "whisper",
  "explorer",
  "bailiff",
  "furrier",
  "locksmith",
  "scholar",
  "composer",
  "rail jack",
  "apiarist",
  "glass blower",
  "magistrate",
  "scribe",
  "steward",
  "soldier"
];

const styles = [
  "tricorn hat",
  "long coat",
  "hood & veil",
  "short cloak",
  "knit cap",
  "slim jacket",
  "hooded coat",
  "tall boots",
  "work boots",
  "mask & robes",
  "suit & vest",
  "collared shirt",
  "suspenders",
  "rough tunic",
  "skirt & blouse",
  "wide belt",
  "fitted dress",
  "heavy cloak",
  "thick greatcoat",
  "soft boots",
  "loose silks",
  "sharp trousers",
  "waxed coat",
  "long scarf",
  "leathers",
  "eelskin bodysuit",
  "hide & furs",
  "uniform",
  "tatters",
  "fitted leggings",
  "apron",
  "heavy gloves",
  "face mask",
  "tool belt",
  "crutches",
  "cane",
  "wheelchair"
];

const traits = [
  "charming",
  "cold",
  "cavalier",
  "brash",
  "suspicious",
  "obsessive",
  "shrewd",
  "quiet",
  "moody",
  "fierce",
  "careless",
  "secretive",
  "ruthless",
  "calculating",
  "defiant",
  "gracious",
  "insightful",
  "dishonest",
  "patient",
  "vicious",
  "suphisticated",
  "paranoid",
  "enthusiastic",
  "elitist",
  "savage",
  "cooperative",
  "arrogant",
  "confident",
  "vain",
  "daring",
  "volatile",
  "candid",
  "subtle",
  "melancholy",
  "enigmatic",
  "calm"
];

const interests = [
  "Fine whiskey, wine, beer",
  "Fine food, restaurants",
  "Fine clothes, jewelry, furs",
  "Fine arts, opera, theater",
  "Painting, drawing, sculpture",
  "History, legends",
  "Architecture, furnishings",
  "Poetry, novels, writing",
  "Pit-fighting, duels",
  "Forgotten gods",
  "Church of Ecstasy",
  "Path of Echoes",
  "Weeping Lady, charity",
  "Antiques, artifacts, curios",
  "Horses, riding",
  "Gadgets, new technology",
  "Weapons collector",
  "Music, instruments, dance",
  "Hunting, shooting",
  "Cooking, gardening",
  "Gambling, cards, dice",
  "Natural philosophy",
  "Drugs, essences, tobacco",
  "Lovers, romance, trysts",
  "Parties, social events",
  "Exploration, adventure",
  "Pets (birds, dogs, cats)",
  "Craft (leatherwork, etc.)",
  "Ships, boating",
  "Politics, journalism",
  "Arcane books, rituals",
  "Spectrology, electroplasm",
  "Alchemy, medicine",
  "Essences, alchemy",
  "Demon lore, legends",
  "Pre-cataclysm legends"
];

const quirks = [
  "Superstitious. Believes in signs, magic numbers.",
  "Devoted to their family.",
  "Married into important / powerful family.",
  "Holds their position to spy for another faction.",
  "Reclusive. Prefers to interact via messengers.",
  "Massive debts (to banks / criminals / family).",
  "Blind to flaws in friends, allies, family, etc.",
  "Once hollowed, then restored. Immune to spirits.",
  "Has chronic illness that requires frequent care.",
  "Secretly (openly?) controlled by posessing spirit.",
  "Serves a demon's agenda (knowingly or not).",
  "Proud of heritage, traditions, native language.",
  "Concerned with appearances, gossip, peers.",
  "Drug / alcohol abuser. Often impaired by their vice.",
  "Holds their position due to blackmail.",
  "Relies on council to make decisions.",
  "Involved with war crimes from the Unity War.",
  "Leads a double life using cover identity.",
  "Black sheep / outcast from family or organization.",
  "In prison or under noble's house arrest.",
  "Well-traveled. Connections outside Doskvol.",
  "Revolutionary. Plots against the Imperium.",
  "Inherited their position. May not deserve / want it.",
  "Celebrity. Popularized in print / song / theater.",
  "Scandalous reputation (deserved or not).",
  "Surrounded by sycophants, supplicants, toadies.",
  "Spotless reputation. Highly regarded.",
  "Bigoted against culture / belief / social class.",
  "Visionary. Holds radical views for future.",
  "Cursed, haunted, harassed by spirits or demon.",
  "Intense, unreasonable phobia or loathing.",
  "Extensive education on every scholarly subject.",
  "Keeps detailed hournals, notes, records, ledgers.",
  "Is blindly faithful to an ideal, group, or tradition.",
  "Deeply traditional. Opposed to new ideas.",
  "A fraud. Some important aspect is fabricated."
];

const firstNames = [
  "Adric",
  "Aldo",
  "Amosen",
  "Andrel",
  "Arden",
  "Arlyn",
  "Arquo",
  "Arvus",
  "Ashlyn",
  "Branon",
  "Brace",
  "Brance",
  "Brena",
  "Bricks",
  "Candra",
  "Carissa",
  "Carro",
  "Casslyn",
  "Cavelle",
  "Clave",
  "Corille",
  "Cross",
  "Crowd",
  "Crowl",
  "Cyrene",
  "Daphnia",
  "Drav",
  "Edlun",
  "Emeline",
  "Grine",
  "Helles",
  "Hix",
  "Holtz",
  "Kamelin",
  "Kelyr",
  "Kobb",
  "Kristov",
  "Laudius",
  "Lauria",
  "Lenia",
  "Lizete",
  "Lorette",
  "Lucella",
  "Lynthia",
  "Mara",
  "Milos",
  "Morlan",
  "Myre",
  "Narcus",
  "Naria",
  "Noggs",
  "Odrienne",
  "Orlan",
  "Phin",
  "Polonia",
  "Quess",
  "Remira",
  "Ring",
  "Roethe",
  "Sesereth",
  "Sethla",
  "Skannon",
  "Stavrul",
  "Stev",
  "Syra",
  "Talitha",
  "Tesslyn",
  "Thena",
  "Timoth",
  "Tocker",
  "Una",
  "Vaurin",
  "Veleris",
  "Veretta",
  "Vestine",
  "Vey",
  "Volette",
  "Vond",
  "Weaver",
  "Wester",
  "Zamira"
];

const lastNames = [
  "Ankhayat",
  "Arran",
  "Athanoch",
  "Basran",
  "Boden",
  "Booker",
  "Bowman",
  "Breakiron",
  "Brogan",
  "Clelland",
  "Clermont",
  "Coleburn",
  "Comber",
  "Daava",
  "Dalmore",
  "Danfield",
  "Dunvil",
  "Farros",
  "Grine",
  "Haig",
  "Helker",
  "Helles",
  "Hellyers",
  "Jayan",
  "Jeduin",
  "Kardera",
  "Karstas",
  "Keel",
  "Kessarin",
  "Kinclaith",
  "Lomond",
  "Maroden",
  "Michter",
  "Morriston",
  "Penderyn",
  "Prichard",
  "Rowan",
  "Sevoy",
  "Skelkallan",
  "Skora",
  "Slane",
  "Strangford",
  "Strathmill",
  "Templeton",
  "Tyrconnell",
  "Vale",
  "Walund",
  "Welker"
];

const aliases = [
  "Bell",
  "Birch",
  "Bricks",
  "Bug",
  "Chime",
  "Coil",
  "Cricket",
  "Cross",
  "Crow",
  "Echo",
  "Flint",
  "Frog",
  "Frost",
  "Grip",
  "Gunner",
  "Hammer",
  "Hook",
  "Junker",
  "Mist",
  "Moon",
  "Nail",
  "Needle",
  "Ogre",
  "Peaches",
  "Pool",
  "Ring",
  "Ruby",
  "Silver",
  "Sixes",
  "Skinner",
  "Song",
  "Spur",
  "Tackle",
  "Thistle",
  "Thorn",
  "Tick-Tock",
  "Twelves",
  "Vixen",
  "Whip",
  "Wicker"
];